services:
  mysql:
    image: mysql:8.0
    container_name: rap-beats-mysql
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rap-beats-root
      MYSQL_DATABASE: rap_beats
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - rap-beats-mysql-data:/var/lib/mysql

volumes:
  rap-beats-mysql-data:

